#pragma once

#include <wrl/client.h>
#include <d3d11_1.h>
#include <DirectXMath.h>
#include <memory>
#include <agile.h>
#include <Direct3DBase.h>
#include <vector>
#include <queue>
#include <string.h>
#include <sqlite3.h>
#include <SpriteBatch.h>
#include <SpriteFont.h>
#include "DatabaseContext.h"
#include "Character.h"
#include "Item.h"
#include "Room.h"
#include "MenuInterface.h"
#include "Inventory.h"